# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/WeKnora"
  cmd = "go build -o  ./tmp/WeKnora -buildvcs=false ./cmd/server"
  include_ext = ["go","tpl","tmpl","html"]
  exclude_dir = ["vendor","tmp"]
  delay = 1000 # 毫秒，文件变动延迟编译
